sudo: required
services:
        - docker
before-install:
        - docker build -t satish -f Dockerfile.dev .
language: generic
script:
        - docker run -e CI=true satish npm run test
deploy:

        provider: elasticbeanstalk
        region: "us-east-1"
        app: "docker-app"
        env: "DockerApp-env"
        bucket_name: "elasticbeanstalk-us-east-1-028811577838"
        bucket_path: "docker-app"
        on:
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY
